global using Xunit;
global using System.Reflection;
global using OpenPlanningPoker.GameEngine.Application.Paging;
global using OpenPlanningPoker.GameEngine.Domain.Abstractions;
global using OpenPlanningPoker.GameEngine.Infrastructure;
global using FluentAssertions;
global using NetArchTest.Rules;
global using FluentValidation;
global using MediatR;